### ISSUE TITLE
Data too big when transaction gets too big (too many UTXOs) 

### ISSUE THREAD

**Issue by msgilligan** [ConsensusJ/wallet-framework#8]
When there are too many UTXOs, exception `com.google.zxing.WriterException: Data too big`  happens.

```
14:52:55 17 UnsignedTxQrGenerator.toJson: txSignReq json: {"header":{"format":"AirgappedSigning","version":1},"transaction":{"uid":"4726207b-c34a-4cf3-9b53-b74f39b9b0a3","asset":"BTCT","inputs":[{"uid":"0476e72a-da33-49a0-96aa-25d7f0e8f7a6","txHash":"c532c825b20644405651b89d38687b4d8ec6f9edf9ccc13c5273e72f33809cd5","sender":"mwAsWXTiRjWnidgU2XepmCReuF4XFtNYV3","derivation":{"accountIndex":0,"addressIndex":11,"isChange":true},"amount":962400,"index":1},{"uid":"18c5e37b-398d-44c8-9c0a-fd84e30be4e1","txHash":"c9b8d6b762851bf22d3afa98d3bfb2f0fd1915a8b4059056769206d1ae9f2d5a","sender":"mqAwsireX8murvZq48LJpppAQdXvT7weA4","derivation":{"accountIndex":0,"addressIndex":17,"isChange":true},"amount":1052788,"index":1},{"uid":"8378e72f-f129-40fb-bfe3-9074a660c8a8","txHash":"0dabeab0a8635e983f61ca59b8819d5e6a6869088a6d35ace6a8525720072418","sender":"mv7ZCfrGwP5ay8rC2Dn2LMh8sDPhavpYrA","derivation":{"accountIndex":0,"addressIndex":15},"amount":1000000,"index":0},{"uid":"b4e57569-6298-4714-bcdc-3b509048cf1e","txHash":"56aeea167dd7c19941bee25a2968ff87cb32188ccefc19f5ac3cffab0e683591","sender":"myQ1RKJhibxSSStVr7DrwZ4Bdg4NdfFeKA","derivation":{"accountIndex":0,"addressIndex":18},"amount":1000000,"index":0},{"uid":"9c97fccc-fafe-465f-8a9b-555924df91b3","txHash":"c36bb53ee6c36d929ca5b888d9f5ab7c72483d7d96f847b2b33aaeba59cd0890","sender":"mqDWvrsz8mHGgrmrTEQzozpTZ3R5jsSUS6","derivation":{"accountIndex":0,"addressIndex":14},"amount":1000000,"index":0},{"uid":"43d151bb-3939-4fab-babf-2cdd22696cb7","txHash":"ee397ae708bd260393460fc1909aac9a9beb7cdce221d23ec7dda0b2d64861c7","sender":"mxHzWzvQf7JQ379DVt9EDdmoHW2AzwvdyV","derivation":{"accountIndex":0,"addressIndex":19},"amount":1000000,"index":0},{"uid":"e06cf7b5-b35a-4721-8ffd-bebfaa719e5f","txHash":"c4fee0ea440bc0fec7e1e69077787e6ed8286973cad9ae5ec0c8030f190a3657","sender":"mq9GZtX1fq2DnerX2Cd8HSAQAVVMmPCVu1","derivation":{"accountIndex":0,"addressIndex":16},"amount":1000000,"index":0},{"uid":"c8679897-fedf-487c-be2c-64492e07f050","txHash":"ee397ae708bd260393460fc1909aac9a9beb7cdce221d23ec7dda0b2d64861c7","sender":"mh4uR2GLQWJycFB6SE1MBxdd12S85EAdTg","derivation":{"accountIndex":0,"addressIndex":19,"isChange":true},"amount":962400,"index":1},{"uid":"f29f0dc9-3f92-4341-9b56-1ab433a52b73","txHash":"54dfb30d7b70eb9219211ed890adf6c8a5fc06523ea569637312b47a51e73fd2","sender":"mhmcgznMbYg4ckMB6ZvoRNea3rAAj1Si8p","derivation":{"accountIndex":0,"addressIndex":12,"isChange":true},"amount":962400,"index":1},{"uid":"76e41a7b-0e8d-46ff-ad2e-4a874e51c186","txHash":"56aeea167dd7c19941bee25a2968ff87cb32188ccefc19f5ac3cffab0e683591","sender":"myCXSZXheu6yXcHtf2TUvPt2jodYdqaLFX","derivation":{"accountIndex":0,"addressIndex":18,"isChange":true},"amount":962400,"index":1},{"uid":"635ac79c-239d-40e8-a668-262383104306","txHash":"c4fee0ea440bc0fec7e1e69077787e6ed8286973cad9ae5ec0c8030f190a3657","sender":"mgp17sWUVrx1Yb9LpqBzAt8iSzNsCHvLpx","derivation":{"accountIndex":0,"addressIndex":16,"isChange":true},"amount":11210647,"index":1},{"uid":"f1421c58-daa7-45c2-8b0d-c8bcb755f0fb","txHash":"c9b8d6b762851bf22d3afa98d3bfb2f0fd1915a8b4059056769206d1ae9f2d5a","sender":"mzFyqtcLU6Gkp9e4qqsGK7buiuH4HEcW1q","derivation":{"accountIndex":0,"addressIndex":17},"amount":100000,"index":0}],"outputs":[{"uid":"d3e87067-d8d8-4ba5-99ee-0c95935dd17a","receiver":"my1RMrv68xwDZLCXgDWKaRanY1Cq1mFsHp","amount":21029835,"derivation":{"accountIndex":0,"addressIndex":0}}]}}
com.google.zxing.WriterException: Data too big
	at org.consensusj.wallet.merged.module/com.google.zxing.qrcode.encoder.Encoder.chooseVersion(Unknown Source)
	at org.consensusj.wallet.merged.module/com.google.zxing.qrcode.encoder.Encoder.recommendVersion(Unknown Source)
	at org.consensusj.wallet.merged.module/com.google.zxing.qrcode.encoder.Encoder.encode(Unknown Source)
	at org.consensusj.wallet.merged.module/com.google.zxing.qrcode.QRCodeWriter.encode(Unknown Source)
	at org.consensusj.wallet.merged.module/com.google.zxing.qrcode.QRCodeWriter.encode(Unknown Source)
	at org.bitcoinj.walletfx/org.bitcoinj.walletfx.utils.QRCodeImages.matrixFromString(Unknown Source)
	at org.bitcoinj.walletfx/org.bitcoinj.walletfx.utils.QRCodeImages.imageFromString(Unknown Source)
	at netwalletfx/netwalletfx.AirGapSigner.displaySigningOverlay(Unknown Source)
```

**Comment by msgilligan** [comment]
![Screen Shot 2019-10-23 at 2 45 00 PM](https://user-images.githubusercontent.com/61612/67437214-2b842400-f5a5-11e9-83fe-045aa3dd9e3d.png)
